################################################################################
#
#  This file is part of SplashSync Project.
#
#  Copyright (C) Splash Sync <www.splashsync.com>
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
#
#  @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################
# Include Pipeline Templates
include:
  - remote: 'https://raw.githubusercontent.com/BadPixxel/Php-Sdk/3.0/gitlab/pages.yaml'

################################################################
# Define Default Image
image: registry.gitlab.com/badpixxel-projects/php-sdk:php-8.0

################################################################
# Set any variables we need
variables:
    # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
    MYSQL_DATABASE:           prestashop
    MYSQL_ROOT_PASSWORD:      admin
    DOCKER_DRIVER:            overlay2
    COMPOSER_MEMORY_LIMIT:    -1
    WEB_DIR:                  /var/www/html
    DB_SERVER:                mysql
    PS_DOMAIN:                localhost
    PS_INSTALL_AUTO:          1
    SPLASH_NO_APACHE:         1
    SPLASH_WS_ID:             ThisIsPsLastKey
    SPLASH_WS_KEY:            ThisTokenIsNotSoSecretChangeIt
    SPLASH_WS_HOST:           http://test.splashsync.local/ws/soap

################################################################
# Defined Pipeline Stages
stages:
  - Quality
  - Functional
  - Builds

################################################################
# Code Quality Tests
################################################################

.quality:   &quality
    stage:      Quality
    tags:       ['Dedicated']
    ################################################################
    # Before Script
    before_script:
        - sh $CI_PROJECT_DIR/ci/before_script.sh
    ################################################################
    # Test Script
    script:
        - sh $CI_PROJECT_DIR/ci/quality.sh
    ################################################################
    # After Script
    after_script:
        - cd $CI_PROJECT_DIR
        - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/after.sh | sh

################################################################
# PrestaShop 9.0
Q-Ps-9.0-Php-8.3:
    image:      prestashop/prestashop:9.0-8.3
    <<: *quality

################################################################
# PrestaShop 8.2
Q-Ps-8.2-Php-8.2:
    image:      prestashop/prestashop:8.2-8.1
    <<: *quality

################################################################
# PrestaShop 8.1
Q-Ps-8.1-Php-8.0:
    image:      prestashop/prestashop:8.1-8.0
    <<: *quality

################################################################
# PrestaShop 8.0
Q-Ps-8.0-Php-8.1:
    image:      prestashop/prestashop:8.0-8.1
    <<: *quality

Q-Ps-8.0-Php-7.4:
    image:      prestashop/prestashop:8.0-7.4
    <<: *quality

################################################################
# PrestaShop 1.7
Q-Ps-1.7-Php-7.4:
    image:      prestashop/prestashop:1.7-7.4
    <<: *quality

################################################################
# Functional Tests
################################################################

.functional:   &functional
    stage:      Functional
    tags:       ['Dedicated']
    retry:      1
    artifacts:
        when: always
        paths:
            - $CI_PROJECT_DIR/splash.json
            - $CI_PROJECT_DIR/splash.yml
        reports:
            junit: "$CI_PROJECT_DIR/*-report.xml"
    services:
        - name: mysql:5.7
    ################################################################
    # Before Script
    before_script:
        - sh $CI_PROJECT_DIR/ci/before_script.sh
    ################################################################
    # Test Script
    script:
        - sh $CI_PROJECT_DIR/ci/functional.sh

################################################################
# PrestaShop 9.0
F-Ps-9.0-Php-8.3:
    image:      prestashop/prestashop:9.0-8.3
    allow_failure:  true
    retry:          0
    <<: *functional

################################################################
# PrestaShop 8.2
F-Ps-8.2-Php-8.2:
    image:      prestashop/prestashop:8.2-8.2
    <<: *functional

################################################################
# PrestaShop 8.1
F-Ps-8.1-Php-8.0:
    image:      prestashop/prestashop:8.1-8.0
    <<: *functional

################################################################
# PrestaShop 8.0
F-Ps-8.0-Php-8.1:
    image:      prestashop/prestashop:8.0-8.1
    <<: *functional

F-Ps-8.0-Php-7.4:
    image:      prestashop/prestashop:8.0-7.4
    <<: *functional

################################################################
# PrestaShop 1.7
F-Ps-1.7-Php-7.4:
    image:      prestashop/prestashop:1.7-7.4
    <<: *functional

################################################################
# Build Documentation
################################################################
module:
    stage:      Builds
    tags:       ['Dedicated']
    retry:      2
    services:
        - docker:dind
    ################################################################################
    # Run Test Script
    script:
        # Run Composer to Build deps
        - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/3.0/ci/composer.sh  | bash
        # Build Documentation
        - php modules/splashsync/vendor/bin/grumphp run --tasks=build-module
    artifacts:
        paths:
            - build
