################################################################################
#
#  This file is part of SplashSync Project.
#
#  Copyright (C) Splash Sync <www.splashsync.com>
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
#
#  @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################
# Set any variables we need
variables:
  # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
  MYSQL_DATABASE:           prestashop
  MYSQL_ROOT_PASSWORD:      admin
  DOCKER_DRIVER:            overlay2
  COMPOSER_MEMORY_LIMIT:    -1
  WEB_DIR:                  /var/www/html
  DB_SERVER:                mysql
  PS_INSTALL_AUTO:          1
  SPLASH_NO_APACHE:         1
  SPLASH_WS_ID:             ThisIsPsLastKey
  SPLASH_WS_KEY:            ThisTokenIsNotSoSecretChangeIt
  SPLASH_WS_HOST:           http://test.splashsync.local/ws/soap

################################################################
# Defined Pipeline Stages
stages:
  - quality
  - functional
  - deploy

################################################################
# Code Quality Tests
################################################################

.quality:   &quality
    stage:      quality
    tags:       ['Dedicated']
    ################################################################
    # Before Script
    before_script:
        - sh $CI_PROJECT_DIR/ci/before_script.sh
    ################################################################
    # Test Script
    script:
        - sh $CI_PROJECT_DIR/ci/quality.sh
    ################################################################
    # After Script
    after_script:
        - cd $CI_PROJECT_DIR
        - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/after.sh | sh

Q-Ps-8.0-Php-8.0:
    image:      prestashop/prestashop:8.0-8.0
    allow_failure:  true
    <<: *quality

Q-Ps-8.0-Php-7.4:
    image:      prestashop/prestashop:8.0-7.4
    <<: *quality

Q-Ps-1.7-Php-7.4:
    image:      prestashop/prestashop:1.7-7.4
    <<: *quality

################################################################
# Functional Tests
################################################################

.functional:   &functional
    stage:      functional
    tags:       ['Dedicated']
    retry:      1
    artifacts:
        when: always
        paths:
            - $CI_PROJECT_DIR/splash.json
            - $CI_PROJECT_DIR/splash.yml
        reports:
            junit: "$CI_PROJECT_DIR/*-report.xml"
    services:
        - name: mysql:5.7
    ################################################################
    # Before Script
    before_script:
        - sh $CI_PROJECT_DIR/ci/before_script.sh
    ################################################################
    # Test Script
    script:
        - sh $CI_PROJECT_DIR/ci/functional.sh


F-Ps-8.0-Php-8.1:
    image:      prestashop/prestashop:8.0-8.1
    allow_failure:  true
    retry:          0
    <<: *functional

F-Ps-8.0-Php-8.0:
    image:      prestashop/prestashop:8.0-8.0
    allow_failure:  true
    retry:          0
    <<: *functional

F-Ps-8.0-Php-7.4:
    image:      prestashop/prestashop:8.0-7.4
    <<: *functional

F-Ps-1.7-Php-7.4:
    image:      prestashop/prestashop:1.7-7.4
    <<: *functional

#################################################################
## Build Documentation
#################################################################
pages:
    image:      registry.gitlab.com/splashsync/php-console:pages
    stage:      deploy
    tags:       ['Dedicated']
    retry:      2
    services:
        - docker:dind
    ################################################################################
    # Run Test Script
    script:
        # Run Composer to Build deps
        - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/composer.sh  | bash
        # Build Documentation
        - php modules/splashsync/vendor/bin/grumphp run --tasks=build-docs
    artifacts:
        paths:
            - public

#################################################################
## Build Documentation
#################################################################
module:
    image:      registry.gitlab.com/splashsync/php-console:pages
    stage:      deploy
    tags:       ['Dedicated']
    retry:      2
    services:
        - docker:dind
    ################################################################################
    # Run Test Script
    script:
        # Run Composer to Build deps
        - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/composer.sh  | bash
        # Build Documentation
        - php modules/splashsync/vendor/bin/grumphp run --tasks=build-module
    artifacts:
        paths:
            - build
